name: CI - Deploy BE to stag env

on:
  push:
    branches:
      - v1.72.0-stable-dev
    paths:
      - "!ui/litellm-dashboard/**"
      - "!.github/workflows/fe-stag.yml"
      - "!.github/workflows/template-docker.yml"
      - "**"

jobs:
  build-docker-x64:
    uses: ./.github/workflows/template-docker.yml
    secrets: inherit
    with:
      runs-on: ubuntu-24-04-docker
      docker-file: Dockerfile
      context: .
      registry-url: registry.menlo.ai
      tags: registry.menlo.ai/library/litellm-be:stag-${{ github.sha }}
      build-args: |
        GIT_COMMIT=${{ github.sha }}
        CONFIG_FILE=configs/jan.yaml
